version: '3'

services:
  db:
    image: postgres:14
    container_name: example
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  db-store: